#!/usr/bin/env bash
# scripts/login.sh — IT-facing one-shot cookies setup / refresh.
#
# Run this on the deploy host (must have a desktop environment + outbound
# internet to google.com and cdn.playwright.dev) when:
#   * you've just unpacked the tarball and run deploy.sh, OR
#   * /api/healthz starts returning auth_valid=false.
#
# It will:
#   1. find the .venv (created by deploy.sh) and the notebooklm CLI inside it
#   2. check Playwright's Chromium can launch; sudo apt install any missing
#      system libs (libnspr4 / libnss3 / ...) after asking you
#   3. open a real Chromium window via `notebooklm login` — sign in with
#      YOUR Google account, open the target notebook once, close the window
#   4. install the resulting cookies as ./secrets/auth.json (mode 0600)
#   5. smoke-test by running `notebooklm list`
#
# Re-running is idempotent: cookies still valid → it offers to skip;
# cookies expired → re-login overwrites in place.
#
# Usage:
#   bash scripts/login.sh                # interactive
#   bash scripts/login.sh --yes          # accept all confirms (non-interactive)
#   bash scripts/login.sh --refresh      # force re-login even if cookies exist
#   bash scripts/login.sh --profile NAME # use a non-default CLI profile

set -uo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
cd "$HERE"

# Load .python-env (generated by check-python.sh) so .venv/bin/python — which
# doesn't carry rpath for self-built interpreters — can find libpython.so /
# libssl.so via LD_LIBRARY_PATH. Absent on hosts using distro Python.
if [ -f "$HERE/.python-env" ]; then
    # shellcheck disable=SC1091
    source "$HERE/.python-env"
fi

# ── Options ────────────────────────────────────────────────
YES=0
FORCE_REFRESH=0
PROFILE="${NOTEBOOKLM_PROFILE:-default}"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --yes|-y) YES=1; shift ;;
        --refresh) FORCE_REFRESH=1; shift ;;
        --profile) PROFILE="$2"; shift 2 ;;
        -h|--help) sed -n '2,25p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# ── Helpers ────────────────────────────────────────────────
say()    { printf '\033[1;34m▶\033[0m %s\n' "$*"; }
ok()     { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn()   { printf '\033[1;33m!\033[0m %s\n' "$*" >&2; }
fail()   { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# Detect the host's distro family so we can pick the right package manager
# command and the right package names for Chromium's shared libs. Reads
# /etc/os-release (set by every modern systemd distro). Output is one of:
#   debian  — Debian, Ubuntu, Linux Mint, etc (apt-get)
#   rhel    — RHEL, CentOS, Rocky, AlmaLinux, Fedora (dnf)
#   suse    — openSUSE Leap/Tumbleweed, SLES (zypper)
#   other   — anything we don't have a package list for; operator handles
detect_distro() {
    if [ -r /etc/os-release ]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        for tag in "${ID:-}" ${ID_LIKE:-}; do
            case "$tag" in
                debian|ubuntu)
                    echo "debian"; return ;;
                rhel|centos|rocky|almalinux|fedora)
                    echo "rhel"; return ;;
                suse|opensuse|opensuse-leap|opensuse-tumbleweed|sles)
                    echo "suse"; return ;;
            esac
        done
    fi
    echo "other"
}

confirm() {
    if [ "$YES" -eq 1 ] || [ ! -t 0 ]; then return 0; fi
    local prompt="$1"
    read -r -p "$prompt [y/N] " resp
    case "$resp" in y|Y|yes|YES) return 0 ;; *) return 1 ;; esac
}

# ── Step 0: preflight ──────────────────────────────────────
say "Step 0/6 — preflight"
[ -f pyproject.toml ] && [ -d scripts ] \
    || fail "Run from the deploy directory (this dir doesn't look like one — no pyproject.toml / scripts/)."

# ── Step 1: locate the venv ────────────────────────────────
say "Step 1/6 — find the venv from deploy.sh"
VENV="$HERE/.venv"
[ -d "$VENV" ] \
    || fail "$VENV not found. Run 'bash deploy.sh' first."
NBLM="$VENV/bin/notebooklm"
[ -x "$NBLM" ] \
    || fail "$NBLM not found. 'bash deploy.sh' may have failed (notebooklm-py[browser,cookies] not installed). Re-run it and watch for errors."

NBLM_VERSION=$("$NBLM" --version 2>&1 | head -1 || true)
ok "${NBLM_VERSION:-notebooklm CLI present}"

# ── Step 2: Playwright Chromium system libs ────────────────
say "Step 2/6 — verify Playwright Chromium can run"
CHROME_BIN=$(ls -1 "$HOME"/.cache/ms-playwright/chromium*/chrome-linux*/chrome 2>/dev/null | head -1 || true)

chrome_missing_libs() {
    [ -n "$CHROME_BIN" ] && [ -x "$CHROME_BIN" ] \
        && ldd "$CHROME_BIN" 2>/dev/null | awk '/=> not found/ {print $1}' | sort -u
}

if [ -z "$CHROME_BIN" ]; then
    # notebooklm-py's CLI does NOT auto-fetch the Chromium binary on first
    # use — it just crashes with BrowserError. So if we hit this branch
    # something went wrong in deploy.sh (which should have run
    # `playwright install chromium`). Fail fast with the correct fix-up
    # command — don't pretend the next step will work.
    fail "Playwright Chromium binary not found under ~/.cache/ms-playwright/.
       deploy.sh should have downloaded it. Re-run deploy.sh, or manually:
         $VENV/bin/playwright install chromium"
else
    MISSING=$(chrome_missing_libs)
    if [ -n "$MISSING" ]; then
        warn "Playwright's bundled Chromium is missing shared libraries:"
        echo "$MISSING" | sed 's/^/      /' >&2

        # Package name lists per distro family. Chromium's runtime needs the
        # same set of libs everywhere (nspr/nss/atk/cairo/pango/alsa/etc), but
        # the package naming convention differs across distros. Keep these
        # lists in sync if Playwright's Chromium bumps its lib requirements.
        DISTRO=$(detect_distro)
        case "$DISTRO" in
            debian)
                PKG_LIST=(
                    libnspr4 libnss3 libdbus-1-3 libatk1.0-0t64 libatk-bridge2.0-0t64
                    libcups2t64 libdrm2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2
                    libasound2t64 libatspi2.0-0t64 libxcomposite1 libxdamage1 libxfixes3
                    libxrandr2 libxshmfence1
                )
                INSTALL_CMD=(sudo apt-get install -y)
                ;;
            rhel)
                # CentOS Stream 9 / RHEL 9 / Rocky 9 / AlmaLinux 9. Some libs
                # (libxshmfence) live in EPEL or CRB on minimal installs — if
                # dnf reports "No match for argument", enable CRB via:
                #   sudo dnf config-manager --set-enabled crb
                # then re-run. We don't auto-enable CRB because some sites lock
                # repo enablement behind change control.
                PKG_LIST=(
                    nspr nss dbus-libs atk at-spi2-atk cups-libs libdrm mesa-libgbm
                    libxkbcommon pango cairo alsa-lib at-spi2-core libXcomposite
                    libXdamage libXfixes libXrandr libxshmfence
                )
                INSTALL_CMD=(sudo dnf install -y)
                ;;
            suse)
                PKG_LIST=(
                    mozilla-nspr mozilla-nss libdbus-1-3 libatk-1_0-0
                    libatk-bridge-2_0-0 libcups2 libdrm2 libgbm1 libxkbcommon0
                    libpango-1_0-0 libcairo2 libasound2 libatspi0
                    libXcomposite1 libXdamage1 libXfixes3 libXrandr2 libxshmfence1
                )
                INSTALL_CMD=(sudo zypper install -y)
                ;;
            other)
                warn "Unknown distro (no /etc/os-release ID match). Can't auto-install Chromium system libs."
                echo ""
                echo "    Try Playwright's own installer for system libs (knows more distros than we do):"
                echo "      sudo $VENV/bin/playwright install-deps chromium    # NB: install-deps = system libs (libnss3 etc),"
                echo "                                                         #     NOT the Chromium binary (deploy.sh handled that)"
                echo "    or see docs/cookie-refresh-runbook.md for the manual lib list."
                fail "Install the deps yourself and re-run scripts/login.sh."
                ;;
        esac

        echo ""
        echo "    Detected distro family: $DISTRO"
        echo "    Need to run:"
        echo "      ${INSTALL_CMD[*]} ${PKG_LIST[*]}"
        echo "    (sudo will prompt for your password on this terminal.)"
        if ! confirm "Run it now?"; then
            fail "Declined. Install the deps yourself and re-run scripts/login.sh."
        fi

        "${INSTALL_CMD[@]}" "${PKG_LIST[@]}" \
            || fail "Package install failed. Fix manually and re-run. (On RHEL 9 minimal: \`sudo dnf config-manager --set-enabled crb\` may be needed before retry.)"

        STILL_MISSING=$(chrome_missing_libs)
        if [ -n "$STILL_MISSING" ]; then
            warn "Still missing after install:"
            echo "$STILL_MISSING" | sed 's/^/      /' >&2
            cat >&2 <<EOF
Chromium still can't load. Two different "playwright install" commands here:
  $VENV/bin/playwright install chromium           — downloads the browser binary
                                                    (deploy.sh already did this;
                                                    re-run only if the binary's broken)
  sudo $VENV/bin/playwright install-deps chromium — installs system libs
                                                    (this is what we just tried;
                                                    if it still fails, see docs/cookie-refresh-runbook.md)
EOF
            fail "Could not fix Chromium's system libs."
        fi
        ok "Chromium deps installed and verified ($DISTRO family)"
    else
        ok "Playwright Chromium deps look fine ($CHROME_BIN)"
    fi
fi

# ── Step 3: notebooklm login (interactive browser) ─────────
say "Step 3/6 — sign in to NotebookLM"
NBLM_HOME="${HOME}/.notebooklm"
NBLM_STATE="$NBLM_HOME/profiles/$PROFILE/storage_state.json"
BRIDGE_AUTH="$HERE/secrets/auth.json"

need_login=1
if [ "$FORCE_REFRESH" -eq 0 ] && [ -f "$NBLM_STATE" ] && [ -f "$BRIDGE_AUTH" ]; then
    warn "Existing cookies found at $NBLM_STATE."
    warn "(If /api/healthz says auth_valid=false you DO need to re-login.)"
    if ! confirm "Re-login anyway?"; then
        need_login=0
        ok "Skipped login; will re-copy existing cookies to secrets/auth.json."
    fi
fi

if [ "$need_login" -eq 1 ]; then
    cat <<EOF

    'notebooklm login' is about to open a real Chromium window. Inside that window:
      1. Sign in with the Google account that owns these notebooks.
      2. Open the target notebook at least once (this seeds notebook-specific cookies).
      3. Close the browser window. The CLI will write:
           $NBLM_STATE

EOF
    if ! confirm "Open the browser now?"; then
        fail "Declined. Re-run scripts/login.sh when ready."
    fi
    "$NBLM" --profile "$PROFILE" login \
        || fail "Login failed. See docs/cookie-refresh-runbook.md for fallbacks."
    [ -f "$NBLM_STATE" ] || fail "Login reported success but $NBLM_STATE is missing."
    ok "Logged in; cookies saved at $NBLM_STATE"
fi

# ── Step 4: copy into secrets/auth.json ────────────────────
say "Step 4/6 — install cookies for the bridge"
mkdir -p "$HERE/secrets"
chmod 700 "$HERE/secrets"
cp "$NBLM_STATE" "$BRIDGE_AUTH"
chmod 600 "$BRIDGE_AUTH"
ok "Copied to $BRIDGE_AUTH (mode 0600)"

# ── Step 5: smoke test ─────────────────────────────────────
say "Step 5/6 — smoke test (notebooklm list)"
if NBLM_LIST_OUTPUT=$("$NBLM" --profile "$PROFILE" list 2>&1); then
    ok "Cookies are working — Google replied with your notebook list:"
    echo "$NBLM_LIST_OUTPUT" | sed 's/^/      | /'
else
    echo "$NBLM_LIST_OUTPUT" | sed 's/^/      | /' >&2
    fail "'notebooklm list' failed. Cookies may be invalid — re-run with --refresh, or see docs/cookie-refresh-runbook.md."
fi

# ── Step 6: next steps ─────────────────────────────────────
say "Step 6/6 — done."
cat <<'EOF'

  Cookies are live. If the bridge is already running, restart it so it picks
  up the new auth.json:

      bash scripts/stop-web.sh && bash scripts/start-web.sh

  Then verify (default backend port 8002; actual port — if start-web.sh had
  to auto-increment — is in .runtime-ports.json, also shown by status-web.sh):

      curl -s http://localhost:8002/api/healthz | jq
      # Expect: auth_valid=true

EOF
